project_id = "qxqvttkcemshgsdobgfe"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.check-subscription]
    verify_jwt = false
  [functions.create-checkout]
    verify_jwt = false
  [functions.customer-portal]
    verify_jwt = false
  [functions.generate-quiz]
    verify_jwt = false
  [functions.send-approval-email]
    verify_jwt = false
  [functions.hub-metrics]
    verify_jwt = false
  [functions.institutional-dashboard]
    verify_jwt = false
  [functions.youtube-transcript]
    verify_jwt = false
  [functions.generate-roadmap]
    verify_jwt = false
  [functions.study-assistant]
    verify_jwt = false
  [functions.preview-transactional-email]
    verify_jwt = false
  [functions.handle-email-events]
    verify_jwt = false
  [functions.send-contact]
    verify_jwt = false
  [functions.send-feedback-email]
    verify_jwt = false
  [functions.generate-project]
    verify_jwt = false
  [functions.generate-simulation]
    verify_jwt = false
  [functions.simulation-step]
    verify_jwt = false
